### ISSUE TITLE
Missing albanian langauge

### ISSUE THREAD

**Issue by diskmanti** [kort/kort-native#53]
There is no option for __albanian__ language on the "Language of the name unknown" mission. Please add the option to input albanian as a language.

Thanks in advance

**Comment by Semigradsky** [comment]
Dublicate https://github.com/kort/kort-native/issues/48

Guys! Could you add more information about 'how' add more languages to https://github.com/kort/kort-core?

**Comment by sfkeller** [comment]
Thanks for your suggestion. Kort translation is based on Transifex. 

Kort development has stalled end of 2017 and there are currently not maintainer nor dev resources available on this project. Around October 2018 there will be some shiny activities in order to resurrect this nice game experience.

So, if you have some spare time, you can head over to https://www.transifex.com/odi/kort/ and start translating right now. Transifex has nice docs. and help pages.

**Comment by sfkeller** [comment]
Closing this issue because it relates to another resource. You can still reopen it if you have questions while translating.
